apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  DB_HOST: dGVycmFmb3JtLWZsYXNrLWFwcC00NDM2MDE6dXMtY2VudHJhbDE6Zmxhc2stc3FsLWluc3RhbmNl
  DB_NAME: ZGIx
  DB_USER: ZGJ1c2VyMQ==
  DB_PASS: ZGJ1c2VyMQ==
